### PR TITLE
Issue fixed

### PR DESCRIPTION
**Pull request by atikmapari**

### CODE REVIEW

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/update-spwopiproofkey.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.es-es/blob/Code-header-fixes/Web-Apps-Server-loc/update-spwopiproofkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/es-es/office/Web-Apps-Server-loc/update-spwopiproofkey?branch=pr-es-es-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C10%5Cde610fbe-32b0-2dfe-cb3b-dc9aabd09165%5CPullRequest%5C201807102204208659-6%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XY2t8Ipsy5bYdIkV1qO1IaI18rqXXAWmPiSZJw6QomE%3D&st=2018-07-10T22%3A00%3A27Z&se=2018-08-10T22%3A05%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.es-es/blob/Code-header-fixes/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/es-es/office/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server?branch=pr-es-es-6) |
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.es-es/blob/Code-header-fixes/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/es-es/office/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013?branch=pr-es-es-6) |
[Web-Apps-Server-loc/deploy-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.es-es/blob/Code-header-fixes/Web-Apps-Server-loc/deploy-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/es-es/office/Web-Apps-Server-loc/deploy-office-web-apps-server?branch=pr-es-es-6) |
[Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.es-es/blob/Code-header-fixes/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/es-es/office/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013?branch=pr-es-es-6) |
[Web-Apps-Server-loc/update-spwopiproofkey.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.es-es/blob/Code-header-fixes/Web-Apps-Server-loc/update-spwopiproofkey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/es-es/office/Web-Apps-Server-loc/update-spwopiproofkey?branch=pr-es-es-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C11%5Cde610fbe-32b0-2dfe-cb3b-dc9aabd09165%5CPullRequest%5C201807110045259697-6%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=adWnTA57bml9yRrt22YjLn9%2FLlWZhTpkcF1VHxH4hBY%3D&st=2018-07-11T00%3A41%3A35Z&se=2018-08-11T00%3A46%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Review by nivnar — CHANGES_REQUESTED** [review]
Please re-send PR with changes on applicable files. Reference files have been removed on master branch

**Review by nivnar — APPROVED** [review]
Removing reference file

**Comment by jmazzotta** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.es-es/blob/Code-header-fixes/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/es-es/office/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server?branch=pr-es-es-6) |
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.es-es/blob/Code-header-fixes/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/es-es/office/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013?branch=pr-es-es-6) |
[Web-Apps-Server-loc/deploy-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.es-es/blob/Code-header-fixes/Web-Apps-Server-loc/deploy-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/es-es/office/Web-Apps-Server-loc/deploy-office-web-apps-server?branch=pr-es-es-6) |
[Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.es-es/blob/Code-header-fixes/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/es-es/office/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013?branch=pr-es-es-6) |
[Web-Apps-Server-loc/update-spwopiproofkey.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.es-es/blob/Code-header-fixes/Web-Apps-Server-loc/update-spwopiproofkey.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C12%5Cde610fbe-32b0-2dfe-cb3b-dc9aabd09165%5CPullRequest%5C201807121847581358-6%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uigzqtJlvgufc4CBGn29RicrwbmABr7As0mVHXnVSqw%3D&st=2018-07-12T18%3A44%3A04Z&se=2018-08-12T18%3A49%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
